### PR TITLE
[mysql-settings] Update mysql settings to closer match acquia, create databases as utf8mb4

### PR DESCRIPTION
**Pull request by JamesDevware**

### CODE REVIEW

**Comment by JamesDevware** [comment]
@jeffgeorge there are a few of these PRs coming breaking them up but trying to get us away from the fork created by robw and back into mainline precip.

**Comment by jeffgeorge** [comment]
Cool. What's the migration process for this pr? Nuke your mysql.vdi while destroyed and re import databases?

**Comment by JamesDevware** [comment]
I didn't even need to nuke the vdi. "Destroy" then "Up" did it so "reload --provision" *may* do it too. I can test that in the near future, probably next week.

**Comment by jeffgeorge** [comment]
Well, but like, if you don't delete databases by zeroing out or nuking the vdi, it won't recreate the databases as utf8mb4, right?

**Comment by JamesDevware** [comment]
That is what I would have expected. But I didn't nuke the VDI, and all of my databases are now utf8mb4. I previously updated Exodus db encoding manually so I would expect this but IET and ZEG are also showing that encoding now and I don't remember changing them manually. Like I say I have destroyed and upped a few times so I will test with a reload next week :)

**Comment by jeffgeorge** [comment]
I had to add the collation (see 53ae683) to get this to work for me, then it was all good.

**Comment by JamesDevware** [comment]
Great thanks!

**Pull request merged**
